### generate product
POST http://localhost:8080/generate/product

### generate user
POST http://localhost:8080/generate/user

### generate n products
POST http://localhost:8080/generate/product/5000

### generate n users
POST http://localhost:8080/generate/user/1000

### 2 task: data generation measurement plot
GET http://localhost:8080/generate/data-generation-plot





### 3 task: select queries execution measurement plot for users
GET http://localhost:8080/queries/query-execute-plot/select
Content-Type: application/json

user

### 3 task: select queries execution measurement plot for products
GET http://localhost:8080/queries/query-execute-plot/select
Content-Type: application/json

product

### 3 task: delete queries execution measurement plot for products
GET http://localhost:8080/queries/query-execute-plot/delete
Content-Type: application/json

user

### 3 task: insert queries execution measurement plot for users
GET http://localhost:8080/queries/query-execute-plot/insert
Content-Type: application/json

user

### 3 task: insert queries execution measurement plot for products
GET http://localhost:8080/queries/query-execute-plot/insert
Content-Type: application/json

product





### 4 task: insert data
GET http://localhost:8080/task4/bInsert

### 4 task: select data
GET http://localhost:8080/task4/bSelect

### 4 task: table sizes chart
GET http://localhost:8080/task4/c




### copy db
POST http://localhost:8080/backup/copyDB

### sandbox
POST http://localhost:8080/backup/sandbox

### restore db
POST http://localhost:8080/backup/restoreDB/dump.sql




### clear user table
POST http://localhost:8080/manage/user

### clear product table
POST http://localhost:8080/manage/product

### replace product data
POST http://localhost:8080/manage/replaceProduct
Content-Type: application/json

[
  {
    "description": "хорошие ботинки",
    "title": "ботинки",
    "price": 12.3,
    "platform": "platform"
  },
  {
    "description": "хорошие ролики",
    "title": "ролики",
    "price": 12.3,
    "platform": "platform"
  }
]

### replace product data
POST http://localhost:8080/manage/replaceUser
Content-Type: application/json

[
  {
    "username": "Sayl",
    "email": "sayl@email.com",
    "password": "examplePassword"
  },
  {
    "username": "Kandid",
    "email": "kandid@email.com",
    "password": "superSecretPassword"
  }
]



### measure query executing time
POST  http://localhost:8080/queries/executeQuery
Content-Type: application/json

SELECT * FROM users;
SELECT * FROM users;
SELECT * FROM users;





### 5 task: a1
GET http://localhost:8080/task5/a1

### 5 task: a2
GET http://localhost:8080/task5/a2

### 5 task: b1
GET http://localhost:8080/task5/b1

### 5 task: b2
GET http://localhost:8080/task5/b2


